### ISSUE TITLE
打不开数据网址

### ISSUE THREAD

**Issue by sybilsibyl** [aaa2222339/machineLearning#12]
我们要用的数据地址是https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz，但发现只有苹果系统可以拿取数据，Windows系统下载不了数据，也打不开这个网址。
报错为网络问题
![image](https://user-images.githubusercontent.com/37989062/94284639-3e596280-ff85-11ea-9c06-64eea1d88808.png)

**Comment by sciengineer-97** [comment]
+ 问题来源：经搜索，该问题和系统无关，主要原因是raw.githubusercontent.com网站在域名解析时受到污染，导致无法获得正确的ip地址。从代码的报错也可以看出：getaddrinfo failed，即没拿到地址信息。

+ 解决办法（2种）

  1. 修改hosts文件，查找raw.githubusercontent.com的对应ip，写入hosts文件

  2. 拿到数据后，放到可以访问的服务器上去。新的地址为http://123.57.133.88/housing.tar，相应的代码修改为

     ```python
     import os
     import tarfile
     from six.moves import urllib
     
     DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
     HOUSING_PATH = "datasets/housing"
     #HOUSING_URL = DOWNLOAD_ROOT + HOUSING_PATH + "/housing.tgz"
     HOUSING_URL = "http://123.57.133.88/housing.tar"
     
     def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
         if not os.path.isdir(housing_path):
             os.makedirs(housing_path)
         
         tgz_path = os.path.join(housing_path, "housing.tgz")
         urllib.request.urlretrieve(housing_url, tgz_path)
         housing_tgz = tarfile.open(tgz_path)
         housing_tgz.extractall(path=housing_path)
         housing_tgz.close()
     
     fetch_housing_data()
     ```
