### ISSUE TITLE
系统选择

### ISSUE THREAD

**Issue by sciengineer-97** [aaa2222339/machineLearning#4]
![image](https://user-images.githubusercontent.com/71587881/93889481-d227f600-fd1b-11ea-87d5-7eaa63ea3909.png)
这个export命令似乎是Linux系统的，windows系统要如何进行本流程？

**Comment by FoolBit** [comment]
有上下文环境和链接吗?
直接看这一句不知道`$HOME`和`$ML_PATH`的作用

**Comment by FoolBit** [comment]
这部分仅用于便捷切换环境，可以直接跳过
第一个指令用于添加环境变量，在windows下可以使用`cmd`中的`set`指令；第二个指令用于创建文件夹，windows下同样为`mkdir`
